title: heartsker/resume
url: "https://github.com/heartsker"
baseurl: "/resume"

markdown: kramdown

tracking_id: 92611710
remote_theme: heartsker/resume@gem

footer: yes
footer_url: "https://github.com/heartsker"
footer_text: "Обновлено 15.05.2024"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Обо мне"
   link: "/resume/"
 - name: "PDF"
   link: "resume_ru.pdf"
 - name: "Контакты"
   link: "contacts"
