title: heartsker/resume
url: "https://github.com/heartsker"
baseurl: "/resume"

markdown: kramdown

tracking_id: 92611710
remote_theme: heartsker/resume@gem

footer: yes
footer_url: "https://github.com/heartsker"
footer_text: "Обновлено 17.12.2023"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Обо мне"
   link: "/resume/"
 - name: "Резюме"
   link: "resume.pdf"
 - name: "Контакты"
   link: "contacts"
